backend/event_manager/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from .services import EventManagerServices
from .models import Message

event_manager = Blueprint("event_manager", __name__)

event_manager_services = EventManagerServices()


@event_manager.route('/manager/home/<string:category>')
@event_manager.route('/manager/home', defaults={"category": 'sports'})
def home(category):
    events = []
    if category:
        events=event_manager_services.fetch_events(category.capitalize())
    else:
        events=event_manager_services.fetch_events()
    
    return render_template('dashboards/event_manager_dashboard.html', events=events)

@event_manager.route('/manager/guest_list/<string:event_id>')
def guest_list(event_id):
    event_guests = event_manager_services.fetch_guest_list(event_id)
    if event_guests:  # Check if event_guests is not empty
        print(event_guests)
        return render_template('notifications/event_guest_list.html', event_id=event_id, event_guests=event_guests)
    else:
        return render_template('notifications/event_guest_list.html', event_id=event_id)

@event_manager.route('/manager/send_message', methods=["GET", "POST"])
def send_message():
    
    if request.method == "POST":
        title = request.form.get('title')
        message = request.form.get('message')
        user_id = request.form.get('user_id')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        username = request.form.get('username')
        
        message = Message(
            sender_id=session['host_id'],
            sender_email=session["host_email"],
            receiver_id=user_id,
            receiver_name=f"{first_name} {last_name}",
            receiver_username=username,
            title=title,
            content=message,
        )
        
        event_manager_services.send_message(message)
        
    return redirect(url_for("event_manager.home"))

backend/shopping_cart/views.py
from random import uniform
import sqlite3

from flask import (
    Blueprint,
    jsonify,
    request,
    redirect,
    url_for,
    session,
    render_template,
    flash,
)
from .forms import AddToCartForm

shopping_cart = Blueprint("shopping_cart", __name__)

@shopping_cart.route("/cart", methods=["GET", "POST"])
def cart():
    if not session["logged_in"]:
        flash("You need to login to view your cart", category="danger")
        return redirect(url_for("auth.login"))
    
    if "shopping_cart" not in session:
        return render_template("shopping_cart/cart.html", shopping_cart={}, total="0.00")
    else:
        return render_template("shopping_cart/cart.html", shopping_cart=session["shopping_cart"]["items"], total=session["shopping_cart"]["total_price"])


@shopping_cart.route("/add_to_cart", methods=["GET", "POST"])
def add_to_cart():
    form = AddToCartForm()
    if request.method == "POST":
        if not session.get("logged_in"):
            flash("You need to login to add items to your cart", category="danger")
            return redirect(url_for("auth.login"))

        # store shopping_cart as hashmap in session
        if "shopping_cart" not in session:
            session["shopping_cart"] = {"items": {}, "total_price": 0.00}

        # get data from form
        event_id = request.form.get("event_id")
        event_name = request.form.get("event_name")
        city = request.form.get("city")
        state = request.form.get("state")
        venue = request.form.get("venue")
        date = request.form.get("date")
        ticket_price = round(uniform(100.00, 800.00), 2)
        ticket_quantity = int(form.quantity.data)

        # Check if the ticket is already in the shopping cart
        if event_id in session["shopping_cart"]["items"]:
            flash("Item already in cart", category="danger")
            return redirect(url_for("event_guest.home"))

        # Add new item to the shopping cart
        new_item = {
            "price": ticket_price,
            "quantity": ticket_quantity,
            "event_id": event_id,
            "event_name": event_name,
            "city": city,
            "state": state,
            "venue": venue,
            "date": date,
        }
        # shopping cart math logic
        session["shopping_cart"]["items"][event_id] = new_item
        session["shopping_cart"]["total_price"] += ticket_price * ticket_quantity

        flash("Item added to cart", category="success")

        session["event_id"] = event_id

        return redirect(url_for("event_guest.home"))


@shopping_cart.route(
    "/remove_from_cart/<string:ticket_id>", methods=["GET", "POST"]
)
def remove_from_cart(ticket_id):
    if not session["logged_in"]:
        flash("You need to login to remove items from your cart", category="danger")
        return redirect(url_for("auth.login"))


    if "shopping_cart" not in session:
        flash("Your shopping cart is empty", category="danger")
        return redirect(url_for("event_guest.home"))

    if ticket_id not in session["shopping_cart"]["items"]:
        flash("Item not found in your cart", category="danger")
        return redirect(url_for("event_guest.home"))

    # Retrieve ticket details
    ticket = session["shopping_cart"]["items"][ticket_id]
    ticket_price = ticket["price"]
    ticket_quantity = ticket["quantity"]

    # Update total price
    session["shopping_cart"]["total_price"] -= ticket_price * ticket_quantity

    # Remove item from the shopping cart
    del session["shopping_cart"]["items"][ticket_id]

    flash("Item removed from your cart", category="success")
    return redirect(url_for("event_guest.home"))


@shopping_cart.route("/cart/clear", methods=["GET", "POST"])
def clear_cart():
    if not session["logged_in"]:
        flash("You need to login to view your cart", category="danger")
        return redirect(url_for("auth.login"))

    if "shopping_cart" in session:
        # Clear the items from the shopping cart
        session["shopping_cart"]["items"] = {}
        # Reset the total price
        session["shopping_cart"]["total_price"] = 0.00
        flash("Your cart has been cleared", category="success")
    else:
        flash("Your shopping cart is already empty", category="warning")

    return redirect(url_for("event_guest.home"))


@shopping_cart.route("/cart/checkout", methods=["GET", "POST"])
def render_checkout():
    if request.method == "GET":
        if not session["logged_in"]:
            flash("You need to login to view your cart", category="danger")
            return redirect(url_for("auth.login"))
        return render_template("shopping_cart/checkout.html")


@shopping_cart.route("/cart/process_payment", methods=["POST"])
def process_payment():

    if request.method == "GET":
        if not session["logged_in"]:
            flash("You need to login to view your cart", category="danger")
            return redirect(url_for("auth.login"))

    data = request.json
    card_number = data.get("cardNumber")
    card_name = data.get("cardName")
    expiry = data.get("expiry")
    cvv = data.get("cvv")
    verify_payment_details(card_number, card_name, expiry, cvv)

    user_id = session["user_id"]
    event_id = session["event_id"]
    guest_name = get_name(user_id)
    insert_into_db(event_id=event_id, user_id=user_id, name=guest_name)
    return redirect(url_for("shopping_cart.payment_sucess"))

@shopping_cart.route("/payment_sucess", methods=["GET"])
def payment_sucess():
    return render_template("shopping_cart/checkout_successful.html")

def get_name(guest_id):
    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    user_id = guest_id

    cursor.execute("SELECT first_name, last_name FROM users WHERE id = ?", (user_id,))
    user_data = cursor.fetchone()

    if user_data:
        first_name, last_name = user_data
        full_name = f"{first_name} {last_name}"  # Concatenate first and last name
        cursor.close()
        conn.close()
        return full_name
    else:
        cursor.close()
        conn.close()
        raise ValueError("User not found")


def verify_payment_details(card_num, name, expiry, cvv):
    return NotImplemented


def insert_into_db(event_id, user_id, name):
    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    print(name)
    cursor.execute(
        "INSERT INTO sold_tickets (guest_id, event_id, guest_name) VALUES (?, ?, ?)",
        (user_id, event_id, name),
    )

    conn.commit()
    conn.close()

backend/templates/dashboards/dashboard.html
{% extends 'index.html' %} {% block title %}<title>Browse Events</title>{%
endblock title%} {% block content %}
<div class="dash-cont">
  <div class="sidebar" id="sidebar">
    <div class="top">
      <div class="logo">
        <i class="bx bxl-codepen"></i>
        <span>Event Ticketing</span>
      </div>
      <i class="bx bx-menu" id="btn"></i>
    </div>
    <div class="user">
      <img
        src="{{ url_for('static', filename='images/venue1.jpg') }}"
        alt="image of a ticket"
        class="user-img"
      />
      <div>
        <p class="bold">E & T</p>
        <p>User</p>
      </div>
    </div>
    <ul>
      <li>
        <a href="/home/sports">
          <i class="bx bx-football"></i>
          <span class="nav-item">Sports</span>
        </a>
        <span class="tooltip">Sports</span>
      </li>
      <li>
        <a href="/home/music">
          <i class="bx bxs-music"></i>
          <span class="nav-item">Concerts</span>
        </a>
        <span class="tooltip">Concerts</span>
      </li>
      <li>
        <a href="/home/fashion">
          <i class="bx bxs-t-shirt"></i>
          <span class="nav-item">Fashion shows</span>
        </a>
        <span class="tooltip">Fashion Shows</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-movie"></i>
          <span class="nav-item">Movies</span>
        </a>
        <span class="tooltip">Movies</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-happy-beaming"></i>
          <span class="nav-item">Festivals</span>
        </a>
        <span class="tooltip">Festivals</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-briefcase-alt-2"></i>
          <span class="nav-item">Conferences</span>
        </a>
        <span class="tooltip">Conferences</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bx-male-female"></i>
          <span class="nav-item">Weddings</span>
        </a>
        <span class="tooltip">Weddings</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-wallet-alt"></i>
          <span class="nav-item">Business events</span>
        </a>
        <span class="tooltip">Business events</span>
      </li>
      <li>
        <a href="/cart">
          <i class="bx bxs-cart-alt"></i>
          <span class="nav-item">Shopping Cart</span>
        </a>
        <span class="tooltip">Shopping Cart</span>
      </li>
    </ul>
  </div>

  <div class="main-content">
    <div class="container">
      <h1>My Dashboard</h1>
      <br />
      <h2>Popular Events:</h2>
      <div
        class="user-dash-cont"
        style="background-color: #1f2937; color: white"
      >
        {% for event in events[:3] %}
        <div>
          <img src="{{ event.image_url }}" alt="image of event" />
          <p>
            {{event.name}}<br />{{ event.city }}, {{ event.state }} <br />Venue:
            {{ event.venue_name }}<br />{{ event.date }}<br />Time: {{
            event.time }}<br />
          </p>
          <br />
          <form
            action="{{ url_for('shopping_cart.add_to_cart') }}"
            method="post"
          >
            {{ form.hidden_tag() }} {# Render any hidden fields included in the
            form #}

            <!-- Hidden fields for additional data -->
            <input type="hidden" name="event_id" value="{{ event.id }}" />
            <input type="hidden" name="event_name" value="{{ event.name }}" />
            <input type="hidden" name="city" value="{{ event.city }}" />
            <input type="hidden" name="state" value="{{ event.state }}" />
            <input type="hidden" name="venue" value="{{ event.venue_name }}" />
            <input type="hidden" name="date" value="{{ event.date }}" />
            <input type="hidden" name="price" value="100" />

            <div class="form-group">
              {# Render the quantity field #} {{ form.quantity.label() }} {{
              form.quantity(class="form-control") }} {% for error in
              form.quantity.errors %}
              <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
            {{ form.submit(class="btn btn-primary") }}
          </form>
        </div>
        {% endfor %}
      </div>
      <div>
        <br />
        <h2>Featured Event:</h2>
        <div class="container1">
          <div class="body-text">
            Join Us For Our <br />
            Featured Event!<br /><br />
            <p>
              Discover a world of excitement with our diverse range of featured
              events! Get ready to groove to the beats of top DJs at our
              electrifying dance parties, challenge yourself with our
              adrenaline-pumping sports tournaments, tantalize your taste buds
              at our gourmet food festivals, or create unforgettable memories
              with your loved ones at our family-friendly carnivals. With an
              array of entertainment options spanning music, sports, food, and
              family fun, there's never a dull moment at our events. Mark your
              calendars and join us for the ultimate experience!"
            </p>
          </div>
          <div class="user-dash-cont" style="color: white">
            {% for event in events[:1] %}
            <div>
              <img src="{{ event.image_url }}" alt="image of event" />
              <p>
                {{event.name}}<br />{{ event.city }}, {{ event.state }}
                <br />Venue: {{ event.venue_name }}<br />{{ event.date }}<br />Time:
                {{ event.time }}<br />
              </p>
              <form
                action="{{ url_for('shopping_cart.add_to_cart') }}"
                method="post"
              >
                {{ form.hidden_tag() }} {# Render any hidden fields included in
                the form #}

                <!-- Hidden fields for additional data -->
                <input type="hidden" name="event_id" value="{{ event.id }}" />
                <input
                  type="hidden"
                  name="event_name"
                  value="{{ event.name }}"
                />
                <input type="hidden" name="city" value="{{ event.city }}" />
                <input type="hidden" name="state" value="{{ event.state }}" />
                <input
                  type="hidden"
                  name="venue"
                  value="{{ event.venue_name }}"
                />
                <input type="hidden" name="date" value="{{ event.date }}" />
                <input type="hidden" name="price" value="100" />

                <div class="form-group">
                  {# Render the quantity field #} {{ form.quantity.label() }} {{
                  form.quantity(class="form-control") }} {% for error in
                  form.quantity.errors %}
                  <span class="text-danger">{{ error }}</span>
                  {% endfor %}
                </div>
                {{ form.submit(class="btn btn-primary") }}
              </form>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <br />
      <h2>Other Awesome Events:</h2>
      <div
        class="user-dash-cont"
        style="background-color: #1f2937; color: white"
      >
        {% for event in events[:9] %}
        <div>
          <img src="{{ event.image_url }}" alt="image of event" />
          <p>
            {{event.name}}<br />{{ event.city }}, {{ event.state }} <br />Venue:
            {{ event.venue_name }}<br />{{ event.date }}<br />Time: {{
            event.time }}<br />
          </p>
          <form
            action="{{ url_for('shopping_cart.add_to_cart') }}"
            method="post"
          >
            {{ form.hidden_tag() }} {# Render any hidden fields included in the
            form #}

            <!-- Hidden fields for additional data -->
            <input type="hidden" name="event_id" value="{{ event.id }}" />
            <input type="hidden" name="event_name" value="{{ event.name }}" />
            <input type="hidden" name="city" value="{{ event.city }}" />
            <input type="hidden" name="state" value="{{ event.state }}" />
            <input type="hidden" name="venue" value="{{ event.venue_name }}" />
            <input type="hidden" name="date" value="{{ event.date }}" />
            <input type="hidden" name="price" value="100" />

            <div class="form-group">
              {# Render the quantity field #} {{ form.quantity.label() }} {{
              form.quantity(class="form-control") }} {% for error in
              form.quantity.errors %}
              <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
            {{ form.submit(class="btn btn-primary") }}
          </form>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<script>
  let btn = document.querySelector("#btn");
  let sidebar = document.querySelector(".sidebar");

  btn.onclick = function () {
    sidebar.classList.toggle("active");
  };

  window.addEventListener("scroll", function () {
    var sidebar = document.getElementById("sidebar");
    var topOffset = 50; // Adjust this value as needed

    if (window.scrollY > topOffset) {
      sidebar.classList.add("fixed");
    } else {
      sidebar.classList.remove("fixed");
    }
  });
</script>
{% endblock content %}

backend/templates/dashboards/event_manager_dashboard.html
{% extends 'index.html' %} {% block content %}

<div class="manager_dash">
  <div class="sidebar" id="sidebar">
    <div class="top">
      <div class="logo">
        <i class="bx bxl-codepen"></i>
        <span>Event Ticketing</span>
      </div>
      <i class="bx bx-menu" id="btn"></i>
    </div>
    <div class="user">
      <img
        src="{{ url_for('static', filename='images/venue1.jpg') }}"
        alt="image of a ticket"
        class="user-img"
      />
      <div>
        <p class="bold">E & T</p>
        <p>User</p>
      </div>
    </div>

    <ul>
      <li>
        <a href="/manager/home/sports">
          <i class="bx bx-football"></i>
          <span class="nav-item">Sports</span>
        </a>
        <span class="tooltip">Sports</span>
      </li>

      <li>
        <a href="/manager/home/music">
          <i class="bx bxs-music"></i>
          <span class="nav-item">Concerts</span>
        </a>
        <span class="tooltip">Concerts</span>
      </li>
      <li>
        <a href="/manager/home/fashion">
          <i class="bx bxs-t-shirt"></i>
          <span class="nav-item">Fashion shows</span>
        </a>
        <span class="tooltip">Fashion Shows</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-movie"></i>
          <span class="nav-item">Movies</span>
        </a>
        <span class="tooltip">Movies</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-happy-beaming"></i>
          <span class="nav-item">Festivals</span>
        </a>
        <span class="tooltip">Festivals</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-briefcase-alt-2"></i>
          <span class="nav-item">Conferences</span>
        </a>
        <span class="tooltip">Conferences</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bx-male-female"></i>
          <span class="nav-item">Weddings</span>
        </a>
        <span class="tooltip">Weddings</span>
      </li>
      <li>
        <a href="#">
          <i class="bx bxs-wallet-alt"></i>
          <span class="nav-item">Business events</span>
        </a>
        <span class="tooltip">Business events</span>
      </li>
    </ul>
  </div>
  <div class="manager_main">
    {% for event in events %}
    <div class="card m-auto" style="width: 36rem">
      <div class="card-body">
        <h5 class="card-title">{{ event.name }}</h5>
        <p class="card-text">{{ event.city }}, {{event.state }}</p>
        <p class="card-text">{{ event.venue }}</p>
        <p class="card-text">{{ event.date }}</p>
        <a
          href="{{ url_for('event_manager.guest_list', event_id=event.id) }}"
          class="btn text-bg-dark"
          >See Guest List</a
        >
      </div>
    </div>
    <br /><br />
    {% endfor %}
  </div>
</div>

<script>
  let btn = document.querySelector("#btn");
  let sidebar = document.querySelector(".sidebar");

  btn.onclick = function () {
    sidebar.classList.toggle("active");
  };

  window.addEventListener("scroll", function () {
    var sidebar = document.getElementById("sidebar");
    var topOffset = 50; // Adjust this value as needed

    if (window.scrollY > topOffset) {
      sidebar.classList.add("fixed");
    } else {
      sidebar.classList.remove("fixed");
    }
  });
</script>
{% endblock content %}